Replaced a few Occurrences mainly in org.graalvm.compiler, since replacements in com.oracle.truffle.api.nodes resulted in too many unexpected errors -> NoClassDefFoundErrors. Also encountered a few IndexOutOfBoundsExceptions during usage of Collections.sort(List) using the Iterator. This was caused by the fact that the SAR used the default implementation of List<E>'s sort method, which possibly caused the error. After Overriding this methode in SARImpl the IndexOutOfBounds reduced to 0 (unfortunately I dont no why atm). Now I am pushing these changes to repo since a full mx unittest runs with only 3 errors. 2 of them i think i can fix. The other one is there every time. (Also with normal ArrayList). Interesting is that data gets generated passively atm since the replacementTest class prints statistics to STOUT. Stunningly about 90% of allocated SSARS have only < 10% LF which is very bad. Now I need do determine if this has something to do with my growing strategy or many replacements with other datatypes should be made